apiVersion: v2
appVersion: 1.6.0
description: A Helm chart for deploying Guacamole, a clientless remote desktop gateway
  that supports standard protocols like VNC, RDP, and SSH.
home: https://guacamole.apache.org/
icon: https://guacamole.apache.org/images/logos/guac-tricolor-logo.svg
name: guacamole
sources:
- https://github.com/apache/guacamole-client
- https://github.com/apache/guacamole-server
type: application
version: 0.0.1
