apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/juusosamuel/pve-guac-solution
      targetRevision: main
      ref: values
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql
      targetRevision: "18.6.7"
      helm:
        valueFiles:
          - $values/postgresql/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true